fix: on-change event in shadowRoot
PolymerElements/iron-autogrow-textarea pull request #122
Opened 2018-07-10 08:27 UTC by AliMD

As you know, In the Shadow DOM, the `change` event is not leaked into the ancestor tree, so we must do this manually.
This is done in the rest of the input components by `paper-input-behavior`.

Fixed https://github.com/PolymerElements/paper-input/issues/664

2018-07-10 08:32 UTC, AliMD commented
@notwaldorf We have an issue in our app and need to fix it as soon as possible
Could you please review/merge this PR with priority
Thank you in advance.

2018-07-10 08:33 UTC, AliMD commented
travis error is not related to this PR changes!

2018-07-17 18:28 UTC, notwaldorf requested changes
(you need to update the typings)

2018-08-07 10:49 UTC, AliMD commented
@notwaldorf 
Oops!
Excuse me.

2018-08-07 11:37 UTC, AliMD commented
@notwaldorf 
I fix the generated declaration manually, but could you please check this issue for future PR?
My generated declaration
`interface IronAutogrowTextareaElement extends Polymer.IronValidatableBehavior, Polymer.IronControlState, Polymer.LegacyElementMixin, HTMLElement {`
Travise
`interface IronAutogrowTextareaElement extends Polymer.Element, Polymer.IronValidatableBehavior, Polymer.IronControlState {`
https://travis-ci.org/PolymerElements/iron-autogrow-textarea/builds/413055027?utm_source=github_status&utm_medium=notification

2018-08-13 19:10 UTC, notwaldorf approved these changes

2018-08-13 19:11 UTC, notwaldorf commented
cc @bicknellr for a release

2023-09-13 22:17 UTC, closed without merging